name: "Build docs for Github Pages"

on:
- push
- workflow_dispatch

jobs:
  build-docs:
    name: Build docs
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v1
      - name: Cache conda packages
        uses: actions/cache@v3
        env:
          # Increase this value to reset cache if environment.yaml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('environment.yaml') }}
      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: "3.11"
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          activate-environment: "ereefs-data-access-notebooks"
          environment-file: environment.yaml

      - shell: bash -el {0}
        run: |
          make dirhtml
